# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0c96ae03c374f62f89a44a299338b4836afcea3a0712727cbbd2232dbc172482f0ba3d6a40b8682500742acec3d7102807676c43ba035201df4883329758214

test:
  secret_key_base: 973be3234611e6905c49cfeda2f5320594876c80e6e5fe2b33db7d7fbbbb2ad9b89a3020ac27fb3f7228680236addf140635d12feba8cbc727ca92e86914e570

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
